version: "3.2"
services:
  autorizador:
    build: ./autorizador
    working_dir: /backend/
    command: sh run.sh
  pacientes:
    build: ./pacientes
    working_dir: /backend/
    command: sh run.sh

  api-gateway:
    image: nginx:latest
    ports:
      - 5000:443
    volumes:
        - ./api-gateway/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
        - ./api-gateway/localhost.crt:/etc/ssl/certs/localhost.crt
        - ./api-gateway/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
        - pacientes
        - autorizador
